language: python
sudo: required
cache: pip

group: deprecated-2017Q2

python:
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch

# command to install dependencies
install:
  - pip install -r requirements.txt
  - python -m spacy download en

services:
  - docker

# Rerun the tests out of the container to get coverage data
script: nosetests --with-coverage unit_tests

after_success:
  - codecov

jobs:
  include:
    - stage: Deploy
      # Install integration testing dependencies and build the docker image
      install: pip install -r requirements.txt && docker build -t willassistant/core:"$TRAVIS_BRANCH" .
      # Unit test the built docker image
      script: docker run willassistant/core:"$1" /bin/sh -c "cd /W.I.L.L/unit_tests; nosetests *.py;"
      # Integration testing
      script: sh create_tests.sh "$DB_PASSWORD" "$TRAVIS_BRANCH"
      # If both stages, pass, push the newly built image to docker hub
      after_success: sh deploy.sh "$TRAVIS_BRANCH" "$DOCKER_USERNAME" "$DOCKER_PASSWORD"

