language: python
sudo: required
cache: pip
python:
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch

# command to install dependencies
install:
  - pip install -r requirements.txt
  - python -m spacy.en.download

services:
  - docker
  - neo4j

# Rerun the tests out of the container to get coverage data
script: nosetests --with-coverage tests

after_success:
  - coverage combine .coveragec
  - codecov

jobs:
  include:
    - stage: Deploy
      install: docker build -t willassistant/core:"$TRAVIS_BRANCH" .
      script: deploy.sh "$TRAVIS_BRANCH" "$DOCKER_USERNAME" "$DOCKER_PASSWORD"

