language: python
sudo: required
cache: pip

python:
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch

services:
  - docker
  - neo4j

jobs:
  include:
    stage: Unit Testing
    install:
      - scripts/build.sh "$TRAVIS_BRANCH"
    script: scripts/test.sh "$TRAVIS_BRANCH"
    deploy:
      skip_cleanup: true
      provider: script
      script: scripts/deploy.sh "$DOCKER_USERNAME" "$DOCKER_PASSWORD" "$TRAVIS_BRANCH"
