language: python
sudo: required
cache: pip

services:
  - docker
  - neo4j

# Rerun the tests out of the container to get coverage data
script: nosetests --with-coverage tests
script: docker run willassistant/core:"$TRAVIS_BRANCH" /bin/sh -c "cd /W.I.L.L/tests; nosetests *.py;"

jobs:
  include:
    stage: Unit Testing
    python:
      - "3.5"
      - "3.5-dev" # 3.5 development branch
      - "3.6"
      - "3.6-dev" # 3.6 development branch
    install:
      - pip install -r requirements.txt
      - python -m spacy.en.download
    script: nosetests --with-coverage tests
    stage: Integration Testing
      install: docker build -t willassistant/core:"$TRAVIS_BRANCH" .
      script: docker run willassistant/core:"$TRAVIS_BRANCH" /bin/sh -c "cd /W.I.L.L/tests; nosetests *.py;"
    deploy:
      skip_cleanup: true
      provider: script
      script: deploy.sh
