language: python
sudo: required
cache: pip
python:
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "3.7-dev" # 3.7 development branch
# command to install dependencies
install:
  - pip install -r requirements.txt
  - python -m spacy.en.download

services:
  - docker

# build the API from the Dockerfile
before_install:
  - docker build -t willassistant/core:"$TRAVIS_BRANCH" .

# command to run tests
script: nosetests --with-coverage tests

after_success:
  - codecov
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push willassistant/core:"$TRAVIS_BRANCH"