language: python
sudo: required
cache: pip
python:
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "3.7-dev" # 3.7 development branch

# command to install dependencies
install:
  - pip install -r requirements.txt
  - python -m spacy.en.download

services:
  - docker
  - neo4j

before_install:
  # Build the API from the Dockerfile
  - docker build -t willassistant/core:"$TRAVIS_BRANCH" .
  # Test run the instance in docker. These tests are the most important, as they're running closer to the prod conf
  - docker run willassistant/core:"$TRAVIS_BRANCH" /bin/sh -c "cd/W.I.L.L/tests; nosetests *.py;"

# Rerun the tests out of the container to get coverage data
script: nosetests --with-coverage tests

after_success:
  - coverage combine .coverage_data
  - codecov

jobs:
  include:
    - stage: Docker Build
      script: docker build -t willassistant/core:"$TRAVIS_BRANCH" .
    - stage: Docker Tests
      script: docker run willassistant/core:"$TRAVIS_BRANCH" /bin/sh -c "cd/W.I.L.L/tests; nosetests *.py;"
    - stage: Docker Push
      script: docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      script: docker push willassistant/core:"$TRAVIS_BRANCH"