language: python
sudo: required
cache: pip
python:
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch

before_install:
  - docker build -t willassistant/core:"$TRAVIS_BRANCH" .

# command to install dependencies
install:
  - pip install -r requirements.txt
  - python -m spacy.en.download

services:
  - docker
  - neo4j

# Rerun the tests out of the container to get coverage data
script: nosetests --with-coverage tests
script: docker run willassistant/core:"$TRAVIS_BRANCH" /bin/sh -c "cd /W.I.L.L/tests; nosetests *.py;"

after_success:
  - coverage combine .coveragec
  - codecov
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push willassistant/core:"$TRAVIS_BRANCH"